In [7]:
import numpy as np
from scipy.stats import t
from scipy.stats import f
from scipy.stats import ttest_ind
from scipy.stats import f_oneway
from scipy.stats import bartlett

def process_file(input_file, output_file):
    # Открытие входного файла для чтения
    with open(input_file, 'r') as f_in:
        # Чтение данных из входного файла
        lines = f_in.readlines()

        # Извлечение первых трёх столбцов и формирование нового массива
        data = []
        for line in lines:
            # Разделение строки по пробелам и преобразование каждого элемента в число
            row = [float(x) for x in line.strip().split()]
            # Извлечение первых трёх элементов
            extracted_row = row[:3]
            data.append(extracted_row)

    # Открытие выходного файла для записи
    with open(output_file, 'w') as f_out:
        # Запись данных в выходной файл
        for row in data:
            # Преобразование элементов строки в строковый формат с точностью до 6 знаков после запятой
            formatted_row = ['%.6f' % x for x in row]
            # Соединение элементов строки через пробел
            line = ' '.join(formatted_row)
            # Запись строки в файл
            f_out.write(line + '\n')


#process_file('norm_unsorted.txt', 'output2.txt')

def process_file_1(input_file, output_file):
    # Открытие входного файла для чтения
    with open(input_file, 'r') as f_in:
        # Чтение данных из входного файла
        lines = f_in.readlines()

        # Формирование нового массива
        data = []
        for line in lines:
            # Разделение строки по пробелам и преобразование каждого элемента в число
            row = [float(x) for x in line.strip().split()]
            data.extend(row)

    # Открытие выходного файла для записи
    with open(output_file, 'w') as f_out:
        # Запись данных в выходной файл
        for item in data:
            # Преобразование элемента в строковый формат с точностью до 6 знаков после запятой
            formatted_item = '%.6f' % item
            # Запись элемента в файл
            f_out.write(formatted_item + '\n')


#process_file_1('output2.txt', 'output3.txt')

with open('norm.txt', 'r') as file:
    norm_data = np.array([float(row.strip()) for row in file])

N = len(norm_data)//3
m = 3
norm_data = norm_data.reshape(N,3)    
with open('normTable.txt','w') as file:
    for row in norm_data:
        for x in row:
            file.write(str(x)+"\t")
        file.write("\n")
    
print(norm_data)

X1, X2, X3 = norm_data[:,0], norm_data[:,1], norm_data[:,2]


[[ 3.07322  1.51317  2.66889]
 [-0.10746  3.77444  3.23707]
 [ 1.03037  2.94085  2.32005]
 [ 1.30789 -0.43326  0.45885]
 [ 2.11064  0.77484  2.23477]
 [ 0.7864   3.68868  1.90816]
 [ 2.75693  2.15845  2.51318]
 [ 1.6277   1.91635  0.15174]
 [-0.85593  0.34195  1.18587]
 [ 2.31516 -0.7214   4.12085]
 [ 2.82519  4.27775  0.82446]
 [ 2.46365  2.61969  3.84731]
 [ 1.90402  2.51901  2.07746]
 [ 1.30448  2.83651  2.32106]
 [-1.05057 -0.80371  0.01518]
 [ 1.29065  0.42748  2.01109]
 [ 0.71323  2.47833  2.89614]
 [ 1.58286  1.54792  1.94523]
 [-0.09015  3.73881  1.87609]
 [ 1.77059  2.23566  3.06231]
 [ 2.01678  0.78148  2.15279]
 [ 1.41523  2.40287  0.06417]
 [ 0.64122  3.20735  1.42562]
 [ 1.8375   1.7357   2.48238]
 [ 0.44692  2.18339  2.42114]
 [ 2.94856  0.76231 -0.35111]
 [-0.52467  2.63768  3.50376]
 [ 3.05184  1.88235  0.21111]
 [ 1.91159  1.85086  2.01751]
 [ 1.36994  2.68434  3.59545]
 [ 1.88455  0.89913  3.71749]
 [ 3.85282  3.08921  3.29263]
 [ 0.89357  2.85372  1.38879]
 [ 0.01689

In [8]:
#Задание1
def getMean(Xlist):
    return round(Xlist.sum()/N, 5)

def getMean2(Xlist):
    res=(Xlist**2).sum()/N
    return round(res,5)

def getS2(mean, mean2):
    res=N/(N-1)*(mean2 - mean**2)
    return round(res,5)

def getT_NM(mean1, S1, mean2, S2):
    res=(mean1 - mean2)/np.sqrt( S1*(N-1)+S2*(N-1) ) 
    res *= np.sqrt( (N*N*(N+N-2))/(N+N) )
    return round(res,5)

meanX1, mean2X1 = getMean(X1), getMean2(X1)
meanX2, mean2X2 = getMean(X2), getMean2(X2)
meanX3, mean2X3 = getMean(X3), getMean2(X3)

S1 = getS2(meanX1, mean2X1)
S2 = getS2(meanX2, mean2X2)
S3 = getS2(meanX3, mean2X3)

T12 = getT_NM(meanX1, S1, meanX2, S2)
T13 = getT_NM(meanX1, S1, meanX3, S3)
T23 = getT_NM(meanX2, S2, meanX3, S3)

t_kr = round( t.ppf(0.975, 2*N-2), 5)

def table1():
    print(f"\nТаблица 1")
    print(f"{meanX1}\t{meanX2}\t{mean2X1}\t{mean2X2}\t{S1}\t{S2}\t{T12}")
    print(f"{meanX1}\t{meanX3}\t{mean2X1}\t{mean2X3}\t{S1}\t{S3}\t{T13}")
    print(f"{meanX2}\t{meanX3}\t{mean2X2}\t{mean2X3}\t{S2}\t{S3}\t{T23}\n")
    
def table2():
    t12, t13, t23 =abs(T12), abs(T13), abs(T23)
    res1="ВЕРНА" if t12 <= t_kr else "НЕВЕРНА"
    res2="ВЕРНА" if t13 <= t_kr else "НЕВЕРНА"
    res3="ВЕРНА" if t23 <= t_kr else "НЕВЕРНА"
    print(f"\nТаблица 2")
    print(f"{t12}\t{t_kr}\t{res1}")
    print(f"{t13}\t{t_kr}\t{res2}")
    print(f"{t23}\t{t_kr}\t{res3}\n")
    
table1()
table2()


Таблица 1
1.44705	1.93058	3.38445	5.48115	1.32276	1.79786	-1.75265
1.44705	1.94018	3.38445	5.0931	1.32276	1.36202	-1.92708
1.93058	1.94018	5.48115	5.0931	1.79786	1.36202	-0.03458


Таблица 2
1.75265	1.99006	ВЕРНА
1.92708	1.99006	ВЕРНА
0.03458	1.99006	ВЕРНА



In [9]:
#Задание 2

def getU():
    u = round(norm_data.sum()/(m*N), 5)
    u_vect = np.zeros(m, float)
    for i in range(m):
        u_vect[i] = norm_data[:,i].sum()/N
    return u, u_vect.round(5)

u, u_vec = getU()
S_ob = ((norm_data-u)**2).sum().round(5)
S_fc = N*((u_vec-u)**2).sum().round(5)
S_ost = round(S_ob-S_fc, 5)

s_fc = round(S_fc/(m-1), 5)
s_ost = round(S_ost/(m*(N-1)), 5)

F_Nm = round(s_fc/s_ost, 5)
k1, k2 = m-1, m*(N-1)

Z = f.ppf(0.95, k1, k2).round(5)

def table3():
    print(f"\nТаблица 3")
    print(f"{S_ob}\t{S_fc}\t{S_ost}\t{s_fc}\t{s_ost}\t{k1}\t{k2}\t{F_Nm}\n")

def table4():
    res="ВЕРНА" if F_Nm <= Z else "НЕВЕРНА"  
    print(f"\nТаблица 4\n{F_Nm}\t{0.05}\t{Z}\t{res}\n")

table3()
table4()


Таблица 3
185.82621	6.51982	179.30639	3.25991	1.49422	2	120	2.18168


Таблица 4
2.18168	0.05	3.07178	ВЕРНА



In [10]:
#Задание 3

pval12 = ttest_ind(X1, X2, equal_var = True).pvalue.round(5)
pval13 = ttest_ind(X1, X3, equal_var = True).pvalue.round(5)
pval23 = ttest_ind(X2, X3, equal_var = True).pvalue.round(5)
a = 0.05
def table5():
    res1 = "ВЕРНА" if pval12 >= a else "НЕВЕРНА"
    res2 = "ВЕРНА" if pval13 >= a else "НЕВЕРНА"
    res3 = "ВЕРНА" if pval23 >= a else "НЕВЕРНА"
    print(f"\nТаблица 5")
    print(f"{pval12}\t{a}\t{res1}")
    print(f"{pval13}\t{a}\t{res2}")
    print(f"{pval23}\t{a}\t{res3}\n")
table5()


Таблица 5
0.0835	0.05	ВЕРНА
0.05752	0.05	ВЕРНА
0.97249	0.05	ВЕРНА



In [11]:
#Задание 4

pval12 = ttest_ind(X1, X2, equal_var = False).pvalue.round(5)
pval13 = ttest_ind(X1, X3, equal_var = False).pvalue.round(5)
pval23 = ttest_ind(X2, X3, equal_var = False).pvalue.round(5)
a = 0.05
def table6():
    res1 = "ВЕРНА" if pval12 >= a else "НЕВЕРНА"
    res2 = "ВЕРНА" if pval13 >= a else "НЕВЕРНА"
    res3 = "ВЕРНА" if pval23 >= a else "НЕВЕРНА"
    print(f"\nТаблица 6")
    print(f"{pval12}\t{a}\t{res1}")
    print(f"{pval13}\t{a}\t{res2}")
    print(f"{pval23}\t{a}\t{res3}\n")
table6()


Таблица 6
0.08358	0.05	ВЕРНА
0.05752	0.05	ВЕРНА
0.97249	0.05	ВЕРНА



In [12]:
#Задание 5

pval = f_oneway(X1, X2, X3).pvalue.round(5)
a = 0.05
def table7():
    res = "ВЕРНА" if pval >= a else "НЕВЕРНА"
    print(f"\nТаблица 7")
    print(f"{pval}\t{a}\t{res}\n")
table7()


Таблица 7
0.1173	0.05	ВЕРНА



In [13]:
#Задание 6

k1, k2 = N-1, N-1
F_Nm1 = round(max(S1, S2)/min(S1,S2), 5)
F_Nm2 = round(max(S1, S3)/min(S1,S3), 5)
F_Nm3 = round(max(S2, S3)/min(S2,S3), 5)


Z = f.ppf(0.975, k1,k2).round(5)

def table8():
    print(f"\nТаблица 8")
    print(f"{S1}\t{S2}\t{k1}\t{k2}\t{F_Nm1}")
    print(f"{S1}\t{S3}\t{k1}\t{k2}\t{F_Nm2}")
    print(f"{S2}\t{S3}\t{k1}\t{k2}\t{F_Nm3}")
    
def table9():
    res1="ВЕРНА" if F_Nm1 <= Z else "НЕВЕРНА"
    res2="ВЕРНА" if F_Nm2 <= Z else "НЕВЕРНА"
    res3="ВЕРНА" if F_Nm3 <= Z else "НЕВЕРНА"
    print(f"\nТаблица 9")
    print(f"{F_Nm1}\t{Z}\t{res1}")
    print(f"{F_Nm2}\t{Z}\t{res2}")
    print(f"{F_Nm3}\t{Z}\t{res3}\n")
    
table8()
table9()


Таблица 8
1.32276	1.79786	40	40	1.35917
1.32276	1.36202	40	40	1.02968
1.79786	1.36202	40	40	1.32

Таблица 9
1.35917	1.8752	ВЕРНА
1.02968	1.8752	ВЕРНА
1.32	1.8752	ВЕРНА



In [14]:
#Задание 7

pval = bartlett(X1, X2, X3).pvalue.round(5)
a = 0.05
def table10():
    res = "ВЕРНА" if pval >= a else "НЕВЕРНА"
    print(f"\nТаблица 10")
    print(f"{pval}\t{a}\t{res}\n")
table10()



Таблица 10
0.55776	0.05	ВЕРНА

